
"ap_esperanza_de_vida"

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggpubr)
library(markdown)
library(shiny)
library(shinythemes)
library(tidyverse)
library(magrittr)
library(lubridate)
library(plotly)
library(xts)
library(dygraphs)
library(kableExtra)
library(knitr)
library("readxl")
library(rsconnect)
library(dplyr)
library(summarytools)
library(epiDisplay)
#library(leaflet)
library(haven)
library(epiDisplay)
library("readxl")
library(expss)
library(hrbrthemes)
library(viridis)
library(viridisLite)
library(DescTools)
library(roperators)
library(shinycssloaders)
library(writexl)
library(labelled)
library(tidyverse)
library(haven)
library(readr)
library(sjmisc)

library(ineq)
library(readstata13)
library(reldist)
library(DT)
library(demography)
```

Pertenece a algun pueblo indigena? cual?

```{r}
ocu <- read_xlsx("esperanza_de_vida.xlsx")
ocu
```

```{r}
ocu1 <- filter(ocu, ocu$año == 2017)
ocu1
```



```{r}
ocu1$cod_com <- as.numeric(ocu1$cod_com)
ocu1
```



se van Cadena, etnia, y se renombra CUT_COM

```{r}
names(ocu1)[1] <- "CUT_COM"
ocu1
```
```{r}
# unique(ocu[,c("Etnia","cod_etnia")])
```

```{r}
# write_xlsx(unique(ocu[,c("Etnia","cod_etnia")]),"codigos_etnia.xlsx")
```

Áreas protegidas

```{r}
ap <- read_xlsx("Tabla_AP_mas_Comunas_Semanario.xlsx") 
ap <- unique(ap)#<<<---------------------------------------------  Se mantienen los datos únicos
ap <- ap[,c(1:12)]
ap
```


```{r} 
codigos_comuna <- unique(ap$CUT_COM)
codigos_comuna
```


El siguiente codigo elimina las AP repetidas:

```{r} 
resultados <- tibble()
for(i in codigos_comuna){
  filtro <- filter(ocu1, CUT_COM == i)
  resultados <- rbind(resultados,filtro)
}
resultados
```

```{r}
ttcc_con_ap <- merge(ap,resultados,by="CUT_COM")
ttcc_con_ap <- unique(ttcc_con_ap)
ttcc_con_ap
```
```{r}
write_xlsx(ttcc_con_ap,"ap_esperanza_de_vida_5.xlsx")
saveRDS(ttcc_con_ap,"ap_esperanza_de_vida_5.rds")
```

```{r}
# f1 <- filter(ttcc_con_ap,ID_AP_Data==99)
# # f1 <- filter(f1,Etnia=="Mapuche")
# # f1 <- filter(f1,Sexo=="Hombre")
# # f1 <- filter(f1,`Sabe leer?`=="Sí")
# # f1 <- filter(f1,variable=="Sí")
# unique(f1)
```
